### ISSUE TITLE
codemods excessively processor intensive

### ISSUE THREAD

**Issue by eccegordo** [ember-cli/ember-cli-update#1016]
Not sure how feasible this is but is there a way to better manage the processor usage?

I have tried to run the codemods and several times now it has just shut down my 16" MBP with 8 cores.

Is there a way to throttle the workers or otherwise apply `nice` constraints to the processes?

The read me doesn't describe how to run the codemods on just a single folder or subset of files. What would really be useful is a selector UI where I could just target which files I want to codemod.

**Comment by kellyselden** [comment]
> Not sure how feasible this is but is there a way to better manage the processor usage?

We're not doing anything special to maximize throughput like threading. So I don't think there's anything to be done.

> I have tried to run the codemods and several times now it has just shut down my 16" MBP with 8 cores.

Do you know which one fails? That sounds like a runaway memory issue in one of the codemods, which should be resolved in that repo.

> The read me doesn't describe how to run the codemods on just a single folder or subset of files. What would really be useful is a selector UI where I could just target which files I want to codemod.

I think if you want that sort of precision, you'd be better off running the codemods manually though their own APIs.

Closing for now because I don't it's something that should be addressed here. Let me know if I'm incorrect.

**Comment by eccegordo** [comment]
Thanks. I will experiment with running the individual codemods in isolation.

I believe the problematic one is the angle brackets HBS conversion. I am seeing all my 32GB of ram fill up and crash computer. If I can reproduce I will post an issue in the specific codemod repo.

I was mostly curious if ember-cli-update offers a flag or argument to only run on a specific folder or subset of files?

**Comment by kellyselden** [comment]
I mentioned that above. I think if you want that sort of precision, you'd be better off running the codemods manually though their own APIs.
