### ISSUE TITLE
Should we allow downgrading?

### ISSUE THREAD

**Issue by BryanCrotaz** [ember-cli/ember-cli-update#376]
addon's package.json lists
`"ember-cli": "~3.2.0"`

Run `ember update --to 3.1.4`

Expected `"ember-cli": "~3.1.4"`
Actual `"ember-cli": "~3.2.0"`

**Comment by kellyselden** [comment]
That's an interesting thought. I had never considered the want to downgrade. I'm not sure if we should attempt to do this or not, because even if we succeeded, codemods may have run and you would now be in an inconsistent state. (codemods don't roll back, except manually yourself via git).

cc @ember-cli/core @ember-cli/core-learning @jenweber @locks since this is a community project now.

**Comment by Turbo87** [comment]
I agree, downgrades should be handled via git or some other source control system. Adding it to ember-cli-update would make it significantly more complex for no significant advantage. We should however display a proper error message telling you that if the user tries to downgrade.

**Comment by BryanCrotaz** [comment]
Or downgrade the npm packages to be kind and warm that any code mods will
need to be reversed by hand.

Bryan Crotaz
Silver Curve

On 8 Jul 2018, at 10:20, Tobias Bieniek <notifications@github.com> wrote:

I agree, downgrades should be handled via git or some other source control
system. Adding it to ember-cli-update would make it significantly more
complex for no significant advantage. We should however display a proper
error message telling you that if the user tries to downgrade.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ember-cli/ember-cli-update/issues/376#issuecomment-403274484>,
or mute the thread

**Comment by kellyselden** [comment]
Closing for now as I don't think it is worth the added complexity.
